"""extend_models_phase3

Revision ID: 34f8474ba9dc
Revises: 02c6e86f62f5
Create Date: 2026-07-26 15:40:34.306218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34f8474ba9dc'
down_revision = '02c6e86f62f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('joining_date', sa.Date(), nullable=False))
        batch_op.create_index(batch_op.f('ix_employees_phone'), ['phone'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)
        batch_op.drop_column('price')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('status')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.drop_column('status')
        batch_op.drop_column('low_stock_threshold')
        batch_op.drop_column('selling_price')
        batch_op.drop_column('cost_price')
        batch_op.drop_column('barcode')
        batch_op.drop_column('sku')
        batch_op.drop_column('category')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_phone'))
        batch_op.drop_column('joining_date')
        batch_op.drop_column('commission_percentage')
        batch_op.drop_column('salary')
        batch_op.drop_column('role')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_column('address')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
