"""extend_membership_phase5

Revision ID: 7cbe57fe700a
Revises: 34f8474ba9dc
Create Date: 2026-07-26 16:01:34.907244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbe57fe700a'
down_revision = '34f8474ba9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('service_discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('product_discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('product_discount_percentage')
        batch_op.drop_column('service_discount_percentage')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
