"""add_branch_management

Revision ID: add_branch_management
Revises: f2aedbe3019b
Create Date: 2026-08-12 11:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_branch_management'
down_revision = 'f2aedbe3019b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add max_branches to subscription_plans (check if column exists first)
    try:
        op.add_column('subscription_plans', sa.Column('max_branches', sa.Integer(), nullable=False, server_default='3'))
    except Exception:
        pass  # Column might already exist
    
    # Create branches table (check if exists first)
    try:
        op.create_table('branches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('phone', sa.String(length=30), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('opening_time', sa.String(length=20), nullable=False, server_default='09:00'),
        sa.Column('closing_time', sa.String(length=20), nullable=False, server_default='20:00'),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='active'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('branches', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_branches_tenant_id'), ['tenant_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_branches_is_deleted'), ['is_deleted'], unique=False)
    except Exception:
        pass  # Table might already exist
    
    # Add branch_id to users table
    try:
        op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_users_branch_id'), ['branch_id'], unique=False)
    except Exception:
        pass
    
    # Add branch_id to customers table
    try:
        op.add_column('customers', sa.Column('branch_id', sa.Integer(), nullable=True))
        with op.batch_alter_table('customers', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_customers_branch_id'), ['branch_id'], unique=False)
    except Exception:
        pass
    
    # Add branch_id to employees table
    try:
        op.add_column('employees', sa.Column('branch_id', sa.Integer(), nullable=True))
        with op.batch_alter_table('employees', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_employees_branch_id'), ['branch_id'], unique=False)
    except Exception:
        pass
    
    # Add branch_id to invoices table
    try:
        op.add_column('invoices', sa.Column('branch_id', sa.Integer(), nullable=True))
        with op.batch_alter_table('invoices', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_invoices_branch_id'), ['branch_id'], unique=False)
    except Exception:
        pass
    
    # Add branch_id to invoice_line_items table
    try:
        op.add_column('invoice_line_items', sa.Column('branch_id', sa.Integer(), nullable=True))
        with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_invoice_line_items_branch_id'), ['branch_id'], unique=False)
    except Exception:
        pass
    
    # Add branch_id to appointments table
    try:
        op.add_column('appointments', sa.Column('branch_id', sa.Integer(), nullable=True))
        with op.batch_alter_table('appointments', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_appointments_branch_id'), ['branch_id'], unique=False)
    except Exception:
        pass
    
    # Add branch_id to appointment_items table
    try:
        op.add_column('appointment_items', sa.Column('branch_id', sa.Integer(), nullable=True))
        with op.batch_alter_table('appointment_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_appointment_items_branch_id'), ['branch_id'], unique=False)
    except Exception:
        pass
    
    # Add branch_id to reminders table
    try:
        op.add_column('reminders', sa.Column('branch_id', sa.Integer(), nullable=True))
        with op.batch_alter_table('reminders', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_reminders_branch_id'), ['branch_id'], unique=False)
    except Exception:
        pass
    
    # Add branch_id to customer_feedback table
    try:
        op.add_column('customer_feedback', sa.Column('branch_id', sa.Integer(), nullable=True))
        with op.batch_alter_table('customer_feedback', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_customer_feedback_branch_id'), ['branch_id'], unique=False)
    except Exception:
        pass
    
    # Add foreign keys after all columns and indexes are created
    try:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_users_branch_id', 'branches', ['branch_id'], ['id'])
    except Exception:
        pass
    
    try:
        with op.batch_alter_table('customers', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_customers_branch_id', 'branches', ['branch_id'], ['id'])
    except Exception:
        pass
    
    try:
        with op.batch_alter_table('employees', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_employees_branch_id', 'branches', ['branch_id'], ['id'])
    except Exception:
        pass
    
    try:
        with op.batch_alter_table('invoices', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_invoices_branch_id', 'branches', ['branch_id'], ['id'])
    except Exception:
        pass
    
    try:
        with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_invoice_line_items_branch_id', 'branches', ['branch_id'], ['id'])
    except Exception:
        pass
    
    try:
        with op.batch_alter_table('appointments', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_appointments_branch_id', 'branches', ['branch_id'], ['id'])
    except Exception:
        pass
    
    try:
        with op.batch_alter_table('appointment_items', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_appointment_items_branch_id', 'branches', ['branch_id'], ['id'])
    except Exception:
        pass
    
    try:
        with op.batch_alter_table('reminders', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_reminders_branch_id', 'branches', ['branch_id'], ['id'])
    except Exception:
        pass
    
    try:
        with op.batch_alter_table('customer_feedback', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_customer_feedback_branch_id', 'branches', ['branch_id'], ['id'])
    except Exception:
        pass
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove branch_id from customer_feedback
    try:
        with op.batch_alter_table('customer_feedback', schema=None) as batch_op:
            batch_op.drop_constraint('fk_customer_feedback_branch_id', type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_customer_feedback_branch_id'))
        op.drop_column('customer_feedback', 'branch_id')
    except Exception:
        pass
    
    # Remove branch_id from reminders
    try:
        with op.batch_alter_table('reminders', schema=None) as batch_op:
            batch_op.drop_constraint('fk_reminders_branch_id', type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_reminders_branch_id'))
        op.drop_column('reminders', 'branch_id')
    except Exception:
        pass
    
    # Remove branch_id from appointment_items
    try:
        with op.batch_alter_table('appointment_items', schema=None) as batch_op:
            batch_op.drop_constraint('fk_appointment_items_branch_id', type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_appointment_items_branch_id'))
        op.drop_column('appointment_items', 'branch_id')
    except Exception:
        pass
    
    # Remove branch_id from appointments
    try:
        with op.batch_alter_table('appointments', schema=None) as batch_op:
            batch_op.drop_constraint('fk_appointments_branch_id', type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_appointments_branch_id'))
        op.drop_column('appointments', 'branch_id')
    except Exception:
        pass
    
    # Remove branch_id from invoice_line_items
    try:
        with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
            batch_op.drop_constraint('fk_invoice_line_items_branch_id', type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_invoice_line_items_branch_id'))
        op.drop_column('invoice_line_items', 'branch_id')
    except Exception:
        pass
    
    # Remove branch_id from invoices
    try:
        with op.batch_alter_table('invoices', schema=None) as batch_op:
            batch_op.drop_constraint('fk_invoices_branch_id', type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_invoices_branch_id'))
        op.drop_column('invoices', 'branch_id')
    except Exception:
        pass
    
    # Remove branch_id from employees
    try:
        with op.batch_alter_table('employees', schema=None) as batch_op:
            batch_op.drop_constraint('fk_employees_branch_id', type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_employees_branch_id'))
        op.drop_column('employees', 'branch_id')
    except Exception:
        pass
    
    # Remove branch_id from customers
    try:
        with op.batch_alter_table('customers', schema=None) as batch_op:
            batch_op.drop_constraint('fk_customers_branch_id', type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_customers_branch_id'))
        op.drop_column('customers', 'branch_id')
    except Exception:
        pass
    
    # Remove branch_id from users
    try:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_constraint('fk_users_branch_id', type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_users_branch_id'))
        op.drop_column('users', 'branch_id')
    except Exception:
        pass
    
    # Drop branches table
    try:
        op.drop_table('branches')
    except Exception:
        pass
    
    # Remove max_branches from subscription_plans
    try:
        op.drop_column('subscription_plans', 'max_branches')
    except Exception:
        pass
    
    # ### end Alembic commands ###