"""extend_settings_phase8

Revision ID: e000b25f6634
Revises: 7cbe57fe700a
Create Date: 2026-07-26 16:54:47.471615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e000b25f6634'
down_revision = '7cbe57fe700a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('alternate_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gst_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('invoice_prefix', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('terms_and_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('show_logo', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('currency_symbol', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('date_format', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('date_format')
        batch_op.drop_column('currency_symbol')
        batch_op.drop_column('show_logo')
        batch_op.drop_column('terms_and_conditions')
        batch_op.drop_column('invoice_prefix')
        batch_op.drop_column('description')
        batch_op.drop_column('website')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('gst_number')
        batch_op.drop_column('alternate_phone')
        batch_op.drop_column('owner_name')

    # ### end Alembic commands ###
