"""add_appointments_and_public_booking

Revision ID: add_appointments_and_public_booking
Revises: e000b25f6634
Create Date: 2026-08-07 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2aedbe3019b'
down_revision = 'e000b25f6634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create appointments table
    op.create_table('appointments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('appointment_number', sa.String(length=100), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('customer_name', sa.String(length=150), nullable=False),
        sa.Column('customer_phone', sa.String(length=50), nullable=False),
        sa.Column('customer_email', sa.String(length=120), nullable=True),
        sa.Column('appointment_date', sa.Date(), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=True),
        sa.Column('end_time', sa.Time(), nullable=True),
        sa.Column('token_number', sa.Integer(), nullable=True),
        sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
        sa.Column('booking_source', sa.String(length=50), nullable=False),
        sa.Column('booking_channel', sa.String(length=50), nullable=False),
        sa.Column('appointment_type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_number'), 'appointments', ['appointment_number'], unique=False)
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointments_customer_phone'), 'appointments', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_appointments_is_deleted'), 'appointments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)

    # Create appointment_items table
    op.create_table('appointment_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('appointment_id', sa.Integer(), nullable=False),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=True),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_items_appointment_id'), 'appointment_items', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_items_employee_id'), 'appointment_items', ['employee_id'], unique=False)
    op.create_index(op.f('ix_appointment_items_service_id'), 'appointment_items', ['service_id'], unique=False)
    op.create_index(op.f('ix_appointment_items_tenant_id'), 'appointment_items', ['tenant_id'], unique=False)

    # Add new columns to tenant_settings
    op.add_column('tenant_settings', sa.Column('allow_staff_selection', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('tenant_settings', sa.Column('booking_enabled', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('tenant_settings', sa.Column('booking_interval_minutes', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('tenant_settings', sa.Column('booking_type', sa.String(length=20), nullable=False, server_default='Token'))
    op.add_column('tenant_settings', sa.Column('break_end_time', sa.String(length=20), nullable=True))
    op.add_column('tenant_settings', sa.Column('break_start_time', sa.String(length=20), nullable=True))
    op.add_column('tenant_settings', sa.Column('closing_time', sa.String(length=20), nullable=False, server_default='20:00'))
    op.add_column('tenant_settings', sa.Column('max_concurrent_slots', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('tenant_settings', sa.Column('max_daily_bookings', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('tenant_settings', sa.Column('opening_time', sa.String(length=20), nullable=False, server_default='09:00'))
    op.add_column('tenant_settings', sa.Column('working_days', sa.Text(), nullable=False, server_default='["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]'))

    # Add new columns to whatsapp_campaigns
    op.add_column('whatsapp_campaigns', sa.Column('template_name', sa.String(length=100), nullable=True))
    op.add_column('whatsapp_campaigns', sa.Column('template_params_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop new columns from whatsapp_campaigns
    op.drop_column('whatsapp_campaigns', 'template_params_json')
    op.drop_column('whatsapp_campaigns', 'template_name')

    # Drop new columns from tenant_settings
    op.drop_column('tenant_settings', 'working_days')
    op.drop_column('tenant_settings', 'opening_time')
    op.drop_column('tenant_settings', 'max_daily_bookings')
    op.drop_column('tenant_settings', 'max_concurrent_slots')
    op.drop_column('tenant_settings', 'closing_time')
    op.drop_column('tenant_settings', 'break_start_time')
    op.drop_column('tenant_settings', 'break_end_time')
    op.drop_column('tenant_settings', 'booking_type')
    op.drop_column('tenant_settings', 'booking_interval_minutes')
    op.drop_column('tenant_settings', 'booking_enabled')
    op.drop_column('tenant_settings', 'allow_staff_selection')

    # Drop appointment_items table
    op.drop_index(op.f('ix_appointment_items_tenant_id'), table_name='appointment_items')
    op.drop_index(op.f('ix_appointment_items_service_id'), table_name='appointment_items')
    op.drop_index(op.f('ix_appointment_items_employee_id'), table_name='appointment_items')
    op.drop_index(op.f('ix_appointment_items_appointment_id'), table_name='appointment_items')
    op.drop_table('appointment_items')

    # Drop appointments table
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_is_deleted'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_phone'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_number'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')

    # ### end Alembic commands ###
